"""remove_tmdb_id_unique

Revision ID: 9f3320e6915e
Revises: bd9787ff13ed
Create Date: 2026-05-28 11:14:02.723222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3320e6915e'
down_revision: Union[str, None] = 'bd9787ff13ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_tmdb_id_key', 'movies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movies_tmdb_id_key', 'movies', ['tmdb_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
