"""Add content_embedding to Movie

Revision ID: c8f1d416cf12
Revises: c7e9f2a4b816
Create Date: 2026-06-11 12:46:37.903450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c8f1d416cf12'
down_revision: Union[str, None] = 'c7e9f2a4b816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('content_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=64),
               nullable=True)
    op.drop_column('movies', 'content_embedding')
    # ### end Alembic commands ###
