"""Add status to watch history

Revision ID: fa64594ae420
Revises: 9f3320e6915e
Create Date: 2026-05-30 02:15:58.037700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa64594ae420'
down_revision: Union[str, None] = '9f3320e6915e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_history', sa.Column('status', sa.String(length=20), server_default='watchlist', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_history', 'status')
    # ### end Alembic commands ###
